=== 502575976/SuperTrumpStarTeamMigration/MoneyCost/SourceCode/FileCopy Service/FileCopySvc/bin/CEFFileCopySvc_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp2 U (http://www.altova.com) by Authorized User (GE Commercial Finance) -->
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Luke Powell (GE Capital Buyers) -->
<!--W3C Schema generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="CONFIG">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DIRS" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="FTP_DIR" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="SRC"/>
										<xs:element ref="DEST"/>
									</xs:sequence>
									<xs:attribute name="ACTION" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="COPY"/>
												<xs:enumeration value="MOVE"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ACTIVE" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="0"/>
												<xs:enumeration value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="HOST" type="xs:string" use="required"/>
									<xs:attribute name="PORT" type="xs:string" use="required"/>
									<xs:attribute name="USER" type="xs:string" use="required"/>
									<xs:attribute name="PASSWORD" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="DIR" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="SRC"/>
										<xs:element ref="DEST"/>
										<xs:element name="FILE_EXT"/>
									</xs:sequence>
									<xs:attribute name="ACTION" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="COPY"/>
												<xs:enumeration value="MOVE"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ACTIVE" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="0"/>
												<xs:enumeration value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="FILES"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DEST">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FILE">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SRC"/>
				<xs:element ref="DEST"/>
			</xs:sequence>
			<xs:attribute name="ACTION" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="COPY"/>
						<xs:enumeration value="MOVE"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ACTIVE" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="0"/>
						<xs:enumeration value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="FILECOPYSVC">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CONFIG"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="FILES">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FILE" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SRC">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== 502575976/SuperTrumpStarTeamMigration/MoneyCost/SourceCode/FileCopy Service/FileCopySvc/bin/CEFFileCopySvc_config_QA.xml
<FILECOPYSVC xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CEFFileCopySvc_config.xsd">
	<CONFIG>
		<FILES>
			<FILE ACTION="COPY" ACTIVE="1">
				<SRC>\\3.61.248.140\Swdist\trikledn\deploy\csvstnew\daily\MCUSD.csv</SRC>
				<DEST>\\cdspmts2ccefge\STServer\MCUSD.csv</DEST>
			</FILE>
			<FILE ACTION="COPY" ACTIVE="1">
				<SRC>\\3.61.248.140\Swdist\trikledn\deploy\csvstnew\daily\MoneyCosts.csv</SRC>
				<DEST>\\cdspmts2ccefge\STServer\MoneyCosts.csv</DEST>
			</FILE>
			<FILE ACTION="COPY" ACTIVE="1">
				<SRC>\\3.61.248.140\Swdist\trikledn\deploy\csvstnew\daily\AniEquity.csv</SRC>
				<DEST>\\cdspmts2ccefge\STServer\AniEquity.csv</DEST>
			</FILE>
			<FILE ACTION="COPY" ACTIVE="1">
				<SRC>\\3.61.248.140\Swdist\trikledn\deploy\csvstnew\daily\MCUSD.csv</SRC>
				<DEST>\\cdsqmts2ccefge\STServer\MCUSD.csv</DEST>
			</FILE>
			<FILE ACTION="COPY" ACTIVE="1">
				<SRC>\\3.61.248.140\Swdist\trikledn\deploy\csvstnew\daily\MoneyCosts.csv</SRC>
				<DEST>\\cdsqmts2ccefge\STServer\MoneyCosts.csv</DEST>
			</FILE>
			<FILE ACTION="COPY" ACTIVE="1">
				<SRC>\\3.61.248.140\Swdist\trikledn\deploy\csvstnew\daily\AniEquity.csv</SRC>
				<DEST>\\cdsqmts2ccefge\STServer\AniEquity.csv</DEST>
			</FILE>
		</FILES>
	</CONFIG>
</FILECOPYSVC>
